version: "3.9"

services:
  db:
    image: postgres:14
    container_name: postgres
    env_file:
        - .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  get_data:
    build:
      context: .
      dockerfile: get_data/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  print_data:
    build:
      context: .
      dockerfile: print_data/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  pg_data:
